#!/bin/bash
set -e

depmod -b "$MODULUS_LD_ROOT"
modprobe -d "$MODULUS_LD_ROOT" udp_tunnel
modprobe -d "$MODULUS_LD_ROOT" ip6_udp_tunnel
depmod -b "$MODULUS_INSTALL_DIR/$DRIVER_NAME"
modprobe -d "$MODULUS_INSTALL_DIR/$DRIVER_NAME" wireguard
